spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ThinkIT
    username: jgm
    password: jgm1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
